import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import { StateProvider } from "./context/State";
import "./globals.css";
import Head from "next/head";

const inter = Bebas_Neue({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    
    <html lang="en">
      
      <body className={inter.className}>
        <StateProvider>{children}</StateProvider>
      </body>
    </html>
    </>
  );
}
